FROM python:3.11-slim
WORKDIR /app

COPY requirements-base.txt requirements-api.txt ./
RUN pip install --no-cache-dir -r requirements-api.txt

COPY alembic.ini ./
COPY alembic ./alembic
COPY app ./app
COPY docker-entrypoint-api.sh ./
RUN chmod +x docker-entrypoint-api.sh

CMD ["./docker-entrypoint-api.sh"]
